# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/Edge_Check_0/Edge_Check_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Edge_Check_0 || ORIG_REF_NAME==Edge_Check_0} -quiet] -quiet
