# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mac/Desktop/project_2/project_2.srcs/sources_1/ip/Shift_Line/Shift_Line.xci
# IP: The module: 'Shift_Line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mac/Desktop/project_2/project_2.srcs/sources_1/ip/Shift_Line/Shift_Line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Shift_Line'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/mac/Desktop/project_2/project_2.srcs/sources_1/ip/Shift_Line/Shift_Line.xci
# IP: The module: 'Shift_Line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mac/Desktop/project_2/project_2.srcs/sources_1/ip/Shift_Line/Shift_Line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Shift_Line'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
