# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/Picture_R_Rom/Picture_R_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Picture_R_Rom || ORIG_REF_NAME==Picture_R_Rom} -quiet] -quiet

# IP: ip/clk_wiz_1/clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_1 || ORIG_REF_NAME==clk_wiz_1} -quiet] -quiet
