# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mac/Desktop/Mini-HDMI-Interface/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/Edge_Check_0/Edge_Check_0.xci
# IP: The module: 'Edge_Check_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/mac/Desktop/Mini-HDMI-Interface/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/Edge_Check_0/src/Shift_Line/Shift_Line.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Shift_Line || ORIG_REF_NAME==Shift_Line} -quiet] -quiet

# IP: c:/Users/mac/Desktop/Mini-HDMI-Interface/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/Edge_Check_0/Edge_Check_0.xci
# IP: The module: 'Edge_Check_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/mac/Desktop/Mini-HDMI-Interface/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/Edge_Check_0/src/Shift_Line/Shift_Line.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Shift_Line || ORIG_REF_NAME==Shift_Line} -quiet] -quiet
