# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mac/Desktop/project_4_1/project_4.srcs/sources_1/ip/Picture_B_Rom/Picture_B_Rom.xci
# IP: The module: 'Picture_B_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mac/Desktop/project_4_1/project_4.srcs/sources_1/ip/Picture_B_Rom/Picture_B_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Picture_B_Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/mac/Desktop/project_4_1/project_4.srcs/sources_1/ip/Picture_B_Rom/Picture_B_Rom.xci
# IP: The module: 'Picture_B_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mac/Desktop/project_4_1/project_4.srcs/sources_1/ip/Picture_B_Rom/Picture_B_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Picture_B_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
